# Generated by Django 5.1.7 on 2025-04-21 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0013_alter_orderitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('movies', 'Movies'), ('music', 'Music'), ('quotes', 'Quotes'), ('family', 'Family'), ('gamers', 'Gamers'), ('sports', 'Sports'), ('funny', 'Funny'), ('spooky', 'Spooky')], max_length=50)),
                ('image', models.ImageField(upload_to='templates/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design_file', models.FileField(blank=True, null=True, upload_to='design_uploads/')),
                ('file_type', models.CharField(blank=True, choices=[('jpeg', 'JPEG'), ('png', 'PNG'), ('svg', 'SVG')], max_length=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Mockup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('gray', 'Gray')], max_length=20)),
                ('size', models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=10)),
                ('mockup_image', models.ImageField(upload_to='mockups/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mockups', to='designs.design')),
            ],
        ),
    ]
